"""The migration chain must build a schema that matches the models."""

from alembic import command

from app.migrations import alembic_config


def test_migrations_match_models(tmp_path):
    """Upgrade a fresh database to head, then let alembic's autogenerate
    diff it against the models: any drift (a model change without a
    migration) fails this test — and therefore CI."""
    cfg = alembic_config(f"sqlite:///{tmp_path / 'migrations.db'}")
    command.upgrade(cfg, "head")
    command.check(cfg)  # raises AutogenerateDiffsDetected on drift


def test_migrations_downgrade_cleanly(tmp_path):
    cfg = alembic_config(f"sqlite:///{tmp_path / 'downgrade.db'}")
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")
